# Generated by Django 4.1.3 on 2023-05-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim Formları'},
        ),
    ]
