# Generated by Django 4.1.3 on 2023-05-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_certificate_socialmedia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Sosyal medya formu Ayarları', 'verbose_name_plural': 'Sosyal medya formu Formu'},
        ),
    ]
