# Generated by Django 4.1.3 on 2023-05-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_socialmedia_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='subject',
        ),
    ]
