# Generated by Django 4.1.3 on 2023-05-18 12:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='', upload_to='images')),
                ('date', models.DateField(auto_now_add=True)),
                ('isHome', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
            ],
        ),
    ]
